school/classroom/urls.py
from django.urls import path
#from .views import home_view
from .views import HomeView,ThankYouView,ContactFormView,TeacherCreateView,TeacherListView,TeacherDetailView,TeacherUpdateView,TeacherDeleteView 

app_name = 'classroom'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('thank_you/',ThankYouView.as_view(),name='thank_you'),
    path('contact/',ContactFormView.as_view(),name='contact'),
    path('create_teacher/',TeacherCreateView.as_view(),name='create_teacher'),
    path('list_teacher/',TeacherListView.as_view(),name='list_teacher'),
    path('teacher_detail/<int:pk>',TeacherDetailView.as_view(),name='detail_teacher'), #send the <int:pk> through the path ALWAYS like this.
    path('update_teacher/<int:pk>',TeacherUpdateView.as_view(),name='update_teacher'),
    path('delete_teacher/<int:pk>',TeacherDeleteView.as_view(),name='delete_teacher'),

]

school/school/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls'))
]

school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches: {self.subject}"

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

school/classroom/views.py
from django.shortcuts import render
#to import a generic template view class,formview
from django.views.generic import TemplateView,FormView,CreateView,ListView,DetailView,UpdateView,DeleteView
#reverselazy to use as successurl
from django.urls import reverse_lazy
#import the formview
from classroom.forms import ContactForm
#import the models for the view
from classroom.models import Teacher


# Create your views here.
""" def home_view(request):
    return render(request,'classroom/home.html')
 """

#to use a template view class
class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'


#model classbasedview create
class TeacherCreateView(CreateView):
    #connect to the model
    model = Teacher
    #the template looks for model_form.html in the app and creates the form 
    #to choose specific fields
    #fields = ['first_name','last_name']
    fields = "__all__"
    success_url = reverse_lazy('classroom:thank_you')

#model classbasedview list
class TeacherListView(ListView):
    model = Teacher
    #to overwrite the query set(Teacher.objects.all()), for example:
    queryset = Teacher.objects.order_by('first_name')
    #to change the use of object_list
    context_object_name = "teacher_list"

class TeacherDetailView(DetailView):
    #looks for a specific template model_detail.html
    model = Teacher
    # searches by PK and sends the teacher

class TeacherUpdateView(UpdateView):
    #shares the createview model and the model_form.html too!! --- PK
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:list_teacher')

class TeacherDeleteView(DeleteView):
    #sends back form with a single confirm delete button
    #model_confirm_delete.html
    model = Teacher
    success_url = reverse_lazy('classroom:list_teacher')




#formview template
class ContactFormView(FormView):
    #connects the form to the formview and the templatename
    form_class = ContactForm 
    template_name = 'classroom/contact.html'
    #success url? actual URL, not the template.html
    #success_url = "/classroom/thank_you"
    #or use reverse lazy
    success_url = reverse_lazy('classroom:thank_you')
    #what to do with the form?
    def form_valid(self,form):
        print(form.cleaned_data)
        #or specific value
        print(form.cleaned_data['name'])
        return super().form_valid(form)

school/classroom/templates/classroom/contact.html
<h1>Form View Template(contact.html)</h1>

<form action="" method="POST">
{%csrf_token%}
{{form.as_p}}
<input type="submit" name="" value="Clic" id="">

</form>

school/classroom/templates/classroom/home.html
<h1>Welcome to Home.html</h1>

<ul>
    <li>
        <a href="{% url "classroom:thank_you" %}">Thank you page link</a>
    </li>
    <li>
        <a href="{% url "classroom:contact" %}">Contact page link</a>
    </li>
    <li>
        <a href="{% url "classroom:create_teacher" %}">Create Teacher page link</a>
    </li>
    <li>
        <a href="{% url "classroom:list_teacher" %}">List Teacher page link</a>
    </li>
</ul>

school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>You sure you want to delete this teacher?</h1>

{{teacher}}

<form action="" method="POST">
{% csrf_token %}

<input type="submit" value="Confirm Delete?">

</form>

school/classroom/templates/classroom/teacher_detail.html
<h1>Detail View for a Teacher</h1>

{{teacher}}

school/classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>

<form action="" method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Clic">

</form>

school/classroom/templates/classroom/teacher_list.html
<h1>Listof Teacher (ListView)</h1>
<!--creating a list with the list model classbasedview-->
<ul>

    <!--object_list is the default but can be changed in the view w/ context_object_name -->
{% for teacher in teacher_list %}
<!--sends the pk through an href-->
    <li>
        <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}} - __str__: {{teacher}}</a>
    </li>
    <ul>
        <li>
        <a href="/classroom/update_teacher/{{teacher.id}}">Update</a>
        </li>
        <li>
        <a href="/classroom/delete_teacher/{{teacher.id}}">Delete</a>
        </li>
    </ul>    
        
{% endfor %}

</ul>

school/classroom/templates/classroom/thank_you.html
<h1>Thank you!</h1>

<ul>
    <li>
        <a href="{% url "classroom:home" %}">Back Home</a>
    </li>

</ul>