my_site3/my_app/urls.py
from django.urls import path
from . import views

#to name the urls. registers the app namespace.
app_name = 'my_app'

urlpatterns = [
    path('example2/',views.example2_view, name = 'example2'),
    path('',views.example_view, name = 'example'),
    path('variable/',views.variable_view, name = 'variable')
]

my_site3/my_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/',include('my_app.urls')),
    
]

handler404 = 'my_app.views.my_custom_page_not_found_view'

my_site3/my_app/models.py
from django.db import models

# Create your models here.

my_site3/my_app/views.py
from django.shortcuts import render

# Create your views here.

def example_view(request):
    return render(request,'my_app/example.html')

def example2_view(request):
    return render(request,'my_app/example2.html')

def variable_view(request):
    #use context to send variables using python
    my_var = {'first_name':'manuel','last_name':'gonzalez',
        'some_list':[1,2,3],'some_dict':{'inside_key':'inside_value'},
        'user_logged_in':True}
    return render(request,'my_app/variable.html',context = my_var)


#to not have to name the template 404
def my_custom_page_not_found_view(request,exception):
    return render(request,'404.html',status=404)

my_site3/my_app/templates/my_app/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>example</h1>
    <h1><a href="{% url 'my_app:variable' %}">click to go to variable</a></h1>
</body>
</html>

my_site3/my_app/templates/my_app/example2.html
{%extends 'base.html'%}
<!--load the static files-->
{%load static %}

{%block content%}

<h1>this is the content in example2</h1>
<img src="{% static 'my_app/django.png' %}" alt="no image">

{% endblock %}

my_site3/my_app/templates/my_app/variable.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user_logged_in %} 
    <h1>Welcome {{first_name}} {{last_name}}</h1> 
    <h1>VARIABLE.HTML</h1> 
    <h2>First name: {{first_name|upper}}</h2>
    <h3>Last name: {{last_name}}</h3> 
    <h2>{{some_list}}</h2>
    <h2>{{some_list.1}}</h2>
    <h2>{{some_dict}}</h2>
    <h2>{{some_dict.inside_key}}</h2>
    <h2>{#this is a comment in django and html using py#}</h2> <!-- same as this -->

    <ul>
    {% for item in some_list %}
    <li><h1>{{item}}</h1></li>
    {% endfor %}
    </ul>

    <ul>
        {% for k,v in some_dict.items %}
        <li><h1>{{k}} : {{v}}</h1></li>
        {% endfor %}
    </ul>

    {% endif %}
</body>
</html>

my_site3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>this is above</h1>
    <!--block and name it-->
    {%block content%}
    

    {%endblock content%}
    <h1>this is below</h1>
</body>
</html>