library/catalog/urls.py
from django.urls import path
from . import views

#app_name = 'catalog'

urlpatterns = [
    path('',views.index,name='index'),
    path('create_book/',views.BookCreate.as_view(),name='create_book'),
    path('book/<int:pk>/',views.BookDetail.as_view(),name='book_detail'),
    path('my_view',views.my_view,name='my_view'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('profile/',views.CheckedOutBookByUserView.as_view(),name='profile')
]

library/library/urls.py
from django.contrib import admin
from django.urls import path,include
#to redirect from home to the app automatically
from django.views.generic import RedirectView

urlpatterns = [

    path('admin/', admin.site.urls),
    path('catalog/',include('catalog.urls')),
    #to redirect from ' ' to the actual app
    path('',RedirectView.as_view(url='catalog/')),
    path('accounts/',include('django.contrib.auth.urls')) #urls set up in the actual source code of django.
    #login,logout,password_change,password_change_done,password_reset,password_reset_done,password_reset_confirm,password_reset_complete 

]

library/catalog/models.py
from django.db import models
from django.urls import reverse
#access to the user model
from django.contrib.auth.models import User

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self): 
        return self.name
        

class Book(models.Model):
    title = models.CharField(max_length=200)
    #what happens if you delete the author? Sets the value to null if the author is deleted. The book survives.
    author = models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)
    summary = models.TextField(max_length=600)
    isbn = models.CharField('ISBN',max_length=13,unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey('Language',on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})



class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True,blank=True)
    
    class Meta:
        ordering = ['last_name','first_name']

    def get_absolute_url(self):
        return reverse("author_detail",kwargs={"pk":self.pk})

    def __str__(self):
        return f"{self.last_name}, {self.first_name}"

import uuid

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    book = models.ForeignKey('Book',on_delete=models.RESTRICT,null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True,blank=True)
    #links borrower and instance to a user as a foreign key
    borrower = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)

    LOAN_STATUS = (
        ('m','Maintenance'),
        ('o','On Loan'),
        ('a','Available'),
        ('r','Reserved')
    )

    status = models.CharField(max_length=1,choices=LOAN_STATUS,blank=True,default='m')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'

library/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Book,Author,BookInstance,Genre,Language
#class based view
from django.views.generic import CreateView,DetailView,ListView
#decorators (required to login to access X page) @login_required in the function
from django.contrib.auth.decorators import login_required
#mixins for class based views to require to authenticate first
from django.contrib.auth.mixins import LoginRequiredMixin
#model form for the userclass. dealing with the form to apply it into a classbasedview
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def index(request):
    #return HttpResponse("Hello")
    #counts the totals
    num_books=Book.objects.all().count() 
    num_instances = BookInstance.objects.all().count()
    num_instances_avail = BookInstance.objects.filter(status__exact='a').count()
    #creates a dictionary with the values and sends them as context to a render request of index.html
    context = {
        'num_books':num_books,
        'num_instances':num_instances,
        'num_instances_avail':num_instances_avail
    }
    
    return render(request,'catalog/index.html',context=context)

#classbasedview
#mixin
class BookCreate(LoginRequiredMixin,CreateView): #model_form.html the default is to go to the BookDetail page (create view below)
    model = Book
    fields = '__all__'

#classbasedview
class BookDetail(DetailView):
    model = Book

#functionbasedview
@login_required
def my_view(request):
    return render(request,'catalog/my_view.html')


class SignUpView(CreateView):
    #overwrites the form class with the usercreationform we imported
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'


class CheckedOutBookByUserView(LoginRequiredMixin,ListView):
    #list all instances but filter by current user session
    model = BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 5 #5 book instances per page

    def get_queryset(self):
        #query that filters out that the borrower is equals to the request user.
        return BookInstance.objects.filter(borrower=self.request.user)

library/catalog/templates/catalog/book_detail.html
<h1>Detail for Book</h1>
{{book}}

<a href="../../">HOME</a>

library/catalog/templates/catalog/book_form.html
<h1>Create new Book</h1>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit" Value="Create">
    
</form>

<a href="../">Back Home</a>

library/catalog/templates/catalog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOMEPAGE</h1>
    <p>Total Books: {{num_books}}</p>
    <p>Num Available: {{num_instances_avail}}</p>
    
    <a href="create_book/">Add Book</a>
    <a href="signup/">Create User</a>
    <a href="profile/">View your Instances</a>

    {% if user.is_authenticated %}
        <p>You are Logged in</p>
        <p>Welcome: {{user.get_username}}</p>
        <a href="{%url 'logout'%}?next={{request.path}}">Log out</a> <!-- Takes you to the home page OR asks to log back in if removed the next-->
    {% else %}
        <p>You are not Logged in</p>
        <a href="{%url 'login'%}?next={{request.path}}">Log in</a>  <!--if you are not logged out you may log out-->
    {% endif %}

</body>
</html>

library/catalog/templates/catalog/my_view.html
<h1>Logged in users only! @login_required "decorator"</h1>

library/catalog/templates/catalog/profile.html
<h1>Profile view</h1>
<h2>Checked out books:</h2>

{% for book in bookinstance_list %}
    <p>{{book}}</p>
{% endfor %}

<a href="../">Back Home</a>

library/catalog/templates/catalog/signup.html
<h1>Register New User</h1>

<form action="" method="POST">
{% csrf_token %}
{{form.as_p}}
<input type="Submit" value="Register User">

</form>

</div>
<a href="../">Back Home</a>