my_car_site/cars/urls.py
from django.urls import path
from . import views
#to use django url names
app_name = 'cars'

urlpatterns = [
    path('list/',views.list,name='list'),
    path('add/',views.add,name='add'),
    path('delete/',views.delete,name='delete'),


]

my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/',include('cars.urls')),
]

my_car_site/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    #PK is not necessary to add it. djang implements it.
    brand = models.CharField(max_length=30)
    year = models.IntegerField()


    def __str__(self):
        return f"Car ID: {self.id} - is a {self.brand} {self.year}"

my_car_site/cars/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from . import models
# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars':all_cars}
    return render(request,'cars/list.html',context=context)

def add(request):
    #check if there is a POST request
    #can be used to check the POST and print it: 
    #print(request.POST)
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand,year=year)
        #asks to redirect to the app name cars name list. defined in urls.py within the app. 
        return redirect(reverse('cars:list'))
    else:
        return render(request,'cars/add.html')


def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse('cars:list'))
        except:
            print('PK not found!')
            return redirect(reverse('cars:list'))
    else:        
        return render(request,'cars/delete.html')

my_car_site/cars/templates/cars/add.html
{% extends "base.html" %}

{%block content%}

<div class="container">
<h1>ADD</h1>

<form action="" method="POST">
    <!--include csrf token for django to allow POST actions-->
    {% csrf_token %}
<div class="form-group">
    <label for="brand">Brand:</label>
    <input class="form-control" type="text" id="brand" name="brand">
</div>

<div class="form-group">
    <label for="year">Year:</label>
    <input class="form-control" type="text" id="year" name="year">
</div>
        <br>
<input class="btn btn-success" type="submit" value="Añadir">
</form>

</div>
{%endblock%}

my_car_site/cars/templates/cars/delete.html
{% extends "base.html" %}

{%block content%}
<div class="container">
<h1>DELETE</h1>
<form action="" method='POST'>
    {% csrf_token %}
    <div class="form-group">
        <label for="pk">Primary Key ID:</label>
        <input class="form-control" type="text" id="pk" name="pk">
    </div>
    <br>
    <input type="submit" class="btn btn-danger">
</form>
</div>
{%endblock%}

my_car_site/cars/templates/cars/list.html
{% extends "base.html" %}

{%block content%}

<div class="container">
<h1>LIST</h1>

<ul>
{%for car in all_cars%}

<li>{{car}}</li>

{% endfor %}
</ul>

</div>
{%endblock%}

my_car_site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

<title>Document</title>

</head>
<body>
    
    <!--NAVBAR-->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'cars:list'%}">LIST</a>
              <a class="nav-link" href="{% url 'cars:add'%}">ADD</a>
              <a class="nav-link" href="{% url 'cars:delete'%}">DELETE</a>

            </div>
          </div>
        </div>
      </nav>
    {%block content%}


    {%endblock%}
</body>
</html>l